# Generated by Django 3.0.5 on 2020-04-23 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeUTEC', models.CharField(max_length=10)),
                ('nTokens', models.IntegerField(default=0)),
                ('typeMember', models.CharField(choices=[('N', 'New'), ('C', 'Copper'), ('S', 'Silver'), ('G', 'Gold')], default='N', max_length=50)),
                ('carrera', models.CharField(choices=[('N', 'Null'), ('EL', 'Electrónica'), ('MT', 'Mecatrónica'), ('IN', 'Industrial')], default='N', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
