# Generated by Django 3.0.5 on 2020-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200424_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
